CLDV6211POEProject/Controllers/Bookings1Controller.cs
using CLDV6211POEProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CLDV6211POEProject.Controllers
{
    public class Bookings1Controller : Controller
    {
        private readonly ApplicationDbContext _context;

        public Bookings1Controller(ApplicationDbContext context)
        {
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var booking = await _context.Bookings1.ToListAsync();
            return View(booking);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Bookings1 booking)
        {

            if (ModelState.IsValid)
            {

                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(booking);
        }

        public async Task<IActionResult> Details(int id)
        {
            var event2 = await _context.Bookings1.FirstOrDefaultAsync(m => m.Booking_Id == id);

            if (event2 == null)
            {

                return NotFound();
            }

            return View(event2);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var booking = await _context.Bookings1.FirstOrDefaultAsync(m => m.Booking_Id == id);

            if (booking == null)
            {

                return NotFound();
            }

            return View(booking);

        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var booking = await _context.Bookings1.FindAsync(id);
            _context.Bookings1.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool EventExist(int id)
        {

            return _context.Bookings1.Any(e => e.Booking_Id == id);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {

                return NotFound();
            }

            var booking = await _context.Bookings1.FindAsync(id);

            if (id == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Bookings1 booking)
        {

            if (id != booking.Booking_Id)
            {

                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!EventExist(booking.Booking_Id))
                    {

                        return NotFound();
                    }
                    else
                    {

                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }
    }
}

CLDV6211POEProject/Controllers/Event1Controller.cs
using CLDV6211POEProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

namespace CLDV6211POEProject.Controllers
{
    public class Event1Controller : Controller
    {

        private readonly ApplicationDbContext _context;

        public Event1Controller(ApplicationDbContext context) 
        {
            _context = context;
        
        }

        public async Task<IActionResult> Index()
        {
            var event1 = await _context.Event1.ToListAsync();
            return View(event1);
        }

        public IActionResult Create() 
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Event1 event2)
        {

            if (ModelState.IsValid)
            {

                _context.Add(event2);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(event2);
        }

        public async Task<IActionResult> Details(int id)
        {
            var event2 = await _context.Event1.FirstOrDefaultAsync(m => m.Event_Id == id); 

            if (event2 == null)
            {

                return NotFound();
            }

            return View(event2);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var event2 = await _context.Event1.FirstOrDefaultAsync(m => m.Event_Id == id);

            if (event2 == null)
            {

                return NotFound();
            }

            return View(event2);

        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var event2 = await _context.Event1.FindAsync(id);
            _context.Event1.Remove(event2);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool EventExist(int id)
        { 
        
        return _context.Event1.Any(e => e.Event_Id == id);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {

                return NotFound();
            }

            var event2 = await _context.Event1.FindAsync(id);

            if (id == null) 
            {
                return NotFound();
            }
            return View(event2);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Event1 event2)
        {

            if (id != event2.Event_Id) 
            {

                return NotFound();
            }

            if (ModelState.IsValid) 
            {
                try
                {

                    _context.Update(event2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) 
                {

                    if (!EventExist(event2.Event_Id))
                    {

                        return NotFound();
                    }
                    else 
                    {

                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(event2);
        }



    }
}

CLDV6211POEProject/Controllers/Venue1Controller.cs
using CLDV6211POEProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CLDV6211POEProject.Controllers
{
    public class Venue1Controller : Controller
    {
        private readonly ApplicationDbContext _context;

        public Venue1Controller(ApplicationDbContext context)
        {
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var venue = await _context.Venue1.ToListAsync();
            return View(venue);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Venue1 venue)
        {

            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(venue);
        }

        public async Task<IActionResult> Details(int id)
        {
            var event2 = await _context.Venue1.FirstOrDefaultAsync(m => m.Venue_Id == id);

            if (event2 == null)
            {

                return NotFound();
            }

            return View(event2);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var venue = await _context.Venue1.FirstOrDefaultAsync(m => m.Venue_Id == id);

            if (venue == null)
            {

                return NotFound();
            }

            return View(venue);

        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var venue = await _context.Venue1.FindAsync(id);
            _context.Venue1.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool EventExist(int id)
        {

            return _context.Venue1.Any(e => e.Venue_Id == id);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {

                return NotFound();
            }

            var venue = await _context.Venue1.FindAsync(id);

            if (id == null)
            {
                return NotFound();
            }
            return View(venue);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Venue1 venue)
        {

            if (id != venue.Venue_Id)
            {

                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!EventExist(venue.Venue_Id))
                    {

                        return NotFound();
                    }
                    else
                    {

                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }
    }
}

CLDV6211POEProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CLDV6211POEProject</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CLDV6211POEProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CLDV6211POEProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event1" asp-action="Index">Event</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venue1" asp-action="Index">Venue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings1" asp-action="Index">Bookings</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CLDV6211POEProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>